### ISSUE TITLE
What cable to use?

### ISSUE THREAD

**Issue by 5-c-o** [oandrew/ipod-gadget#14]
What cable is best for this?

My car uses a provided MDI (Media Device Interface) to lightning male adapter. Connecting via the USB adapter with a standard lightning to usb lead doesn't work (for iPhones/iPods.)

So I'm assuming I'm gonna need a USB male (Pi) to lightning female (car) cable/adapter?

**Comment by Kytech** [comment]
I'm not certain if this would work, but I'm thinking your best option is probably going to be to find an MDI to USB female cable with iPod/iPhone support. I don't own a car that uses MDI, so I can't test this myself. (Some MDI to USB cables only support MDI to USB for flash drive support only). These cables that support MDI to USB female should allow an iPod/iPhone to work by going from MDI -> USB -> iPod (Using standard provided charging/computer lightning cable). If you find an MDI to USB cable that can support this kind of connection, theoretically, it should work with this project by replacing the iPod with a Pi since this program emulates the iPod. The final hookup would be MDI -> USB (with iPod support) -> Pi (using a USB-A to Micro USB-B, like those that are common for cell phone chargers.)

These type of MDI cables may be fairly difficult to come by, so a USB Micro B to female lightning could work since that should just pass through the standard data lines. However, a female lightning to USB micro B doesn't seem to be very common, though to USB C is common. They do have female USB C to male micro B adapters. These should pass the data lines untouched. That's a lot of adapters though, so this may not work. Sounds like lightning to USB can be tricky at times based on what you said.

You can give this a shot since there's a chance it may work, but you may just be better off buying an MDI to 30pin cable and purchasing an iPod 30pin to Bluetooth adapter if you just want to get sound to your car from a Smartphone.
